# Generated by Django 3.1 on 2021-01-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='title_kana',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
