# Generated by Django 3.1 on 2021-02-17 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animeval', '0002_animemodel_title_kana'),
    ]

    operations = [
    ]
